spring.jpa:
  show-sql: true
  hibernate.ddl-auto: create-drop

spring.datasource:
  platform: h2
  url: jdbc:h2:mem:hello-world

spring.h2.console.enabled: true

server:
  port: 8080

spring.security.oauth2.resourceserver.jwt.jwk-set-uri: https://www.googleapis.com/service_accounts/v1/jwk/securetoken%40system.gserviceaccount.com

cors.allowed.origins: ${CORS_ALLOWED_ORIGINS}